import { StarRating, RatingReaction } from '../types/feedback';

export const SHINCHAN_REACTIONS: Record<StarRating, RatingReaction> = {
  1: {
    rating: 1,
    label: 'Crying & Devastated',
    subtitle: 'Shin-chan is bawling his eyes out and terrified Misae will scold him!',
    shinchanQuote: 'Aiyo... Did I mess up? Please don\'t leave me like this, big brother/sister! 😭',
    japanesePhrase: 'Mou dame da zo... (It\'s hopeless...)',
    moodColor: '#2563EB',
    bgColor: '#EFF6FF',
    accentBg: '#DBEAFE',
    borderColor: '#BFDBFE',
  },
  2: {
    rating: 2,
    label: 'Pouting & Grumpy',
    subtitle: 'Shin-chan crossed his arms and is grumbling in protest.',
    shinchanQuote: 'Hmph! Not even Bo-chan\'s weird rock collection is this boring! 😒',
    japanesePhrase: 'Fuuun da! (Hmph, whatever!)',
    moodColor: '#D97706',
    bgColor: '#FFFBEB',
    accentBg: '#FEF3C7',
    borderColor: '#FDE68A',
  },
  3: {
    rating: 3,
    label: 'Sly & Curious',
    subtitle: 'Shin-chan is scratching his cheek, thinking it was average.',
    shinchanQuote: 'Hmm... Not bad! How about we pause this and grab some Chocobi biscuits? 🍪',
    japanesePhrase: 'Maa maa da zo! (Just so-so!)',
    moodColor: '#0D9488',
    bgColor: '#F0FDFA',
    accentBg: '#CCFBF1',
    borderColor: '#99F6E4',
  },
  4: {
    rating: 4,
    label: 'Cheerful & Grinning',
    subtitle: 'Shin-chan is blushing with happy cheeks and giving a thumbs up!',
    shinchanQuote: 'Ooh la la! Don\'t praise me too much, you\'re making me blush! Hehehe! ✨',
    japanesePhrase: 'Sore hodo demo aru zo! (Don\'t flatter me!)',
    moodColor: '#EA580C',
    bgColor: '#FFF7ED',
    accentBg: '#FFEDD5',
    borderColor: '#FED7AA',
  },
  5: {
    rating: 5,
    label: 'Action Kamen Victory!',
    subtitle: 'Shin-chan is doing the celebratory victory dance with sparkling eyes!',
    shinchanQuote: 'ACTION KAMEN BEAM!! ⚡ WAHAHAHA! Maximum score! You\'re the best ever! 🎉',
    japanesePhrase: 'Akushon Kamen da zo!! (Action Kamen power!)',
    moodColor: '#E11D48',
    bgColor: '#FFF1F2',
    accentBg: '#FFE4E6',
    borderColor: '#FECDD3',
  },
};
